---
# ----------------------------------------------------------------------------------------
# -- Docs: https://github.com/cluster-apps-on-docker/spark-standalone-cluster-on-docker --
# ----------------------------------------------------------------------------------------
version: "3.6"
volumes:
  shared-workspace:
    name: "shared-workspace"
    driver: local
  hadoop-distributed-file-system:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  jupyterlab:
    image: gdistories/jupyterlab:dsaa5021
    container_name: jupyterlab
    working_dir: /root
    ports:
      - "8889:8888"
      - "4041:4040"
      - "22000:22"
    volumes:
      - shared-workspace:/opt/workspace
      - hadoop-distributed-file-system:/root/shared-workspace
      - ./:/root/local-workspace
  spark-master:
    image: gdistories/spark-master:dsaa5021
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - shared-workspace:/opt/workspace
      - hadoop-distributed-file-system:/root/shared-workspace
      - ./:/root/local-workspace
  spark-worker-1:
    image: gdistories/spark-worker:dsaa5021
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=4g
    ports:
      - "8081:8081"
    volumes:
      - shared-workspace:/opt/workspace
      - hadoop-distributed-file-system:/root/shared-workspace
      - ./:/root/local-workspace
    depends_on:
      - spark-master
  spark-worker-2:
    image: gdistories/spark-worker:dsaa5021
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=4g
    ports:
      - "8082:8081"
    volumes:
      - shared-workspace:/opt/workspace
      - hadoop-distributed-file-system:/root/shared-workspace
      - ./:/root/local-workspace
    depends_on:
      - spark-master
  spark-worker-3:
    image: gdistories/spark-worker:dsaa5021
    container_name: spark-worker-3
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=4g
    ports:
      - "8083:8081"
    volumes:
      - shared-workspace:/opt/workspace
      - hadoop-distributed-file-system:/root/shared-workspace
      - ./:/root/local-workspace
    depends_on:
      - spark-master
...
